### ISSUE TITLE
 [Error 5] Access is denied See log for more details

### ISSUE THREAD

**Issue by tveinot** [Oslandia/qgis-epanet#12]
Running the tool on the test data and getting an error;

Algorithm Simulate flow in drinking water network starting...
running simulation

[Error 5] Access is denied See log for more details

I have EPANET2 installed and the plugin set to my install directory for EPANET2 where the .exe file resides. I don't see a commandline tool in this directory, or anywhere on my PC. This might be the issue but the only EPANET tool I could find was here...
https://www.epa.gov/water-research/epanet#downloads

Is there something else I am too have installed? The link on the readme takes me to a 404 error.
Thanks
Tyler

**Comment by vmora** [comment]
The command line tool is `epanet2d.exe` and should be in the same directory as `Epanet2w.exe` (the latter beeing the GUI which we don't use).

There are detailed installation instructions here  http://oslandia.com/fr/2014/04/25/premiers-pas-avec-qgis-epanet/ (the text is in french though)

There are several links in the Readme, could you plz precise which one is invalid ?

**Comment by tveinot** [comment]
The bad link is this one;
http://www.epa.gov/nrmrl/wswrd/dw/epanet/EN2setup.exe
Found in the readme on github at https://github.com/Oslandia/qgis-epanet, I didn't see it in your link so maybe the readme I was using is depreciated.
The French Installations Instructions got me past the access denied error; I saw in the images that for the path they included epanet2d.exe where I only included up to the directory location. When I run it now it gives me a "There are errors, please check the processing log..." so I am about to do that now.
Thanks for the help.
Tyler

**Comment by vmora** [comment]
To test your installation, you can use this example:

https://github.com/Oslandia/qgis-water-management-cookbook/tree/master/simple_network

**Comment by vmora** [comment]
BTW I fixed the dead link, thanks for the repport.
